//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPFinal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("567, 285")]
        public global::System.Drawing.Size Form_EquipeSize {
            get {
                return ((global::System.Drawing.Size)(this["Form_EquipeSize"]));
            }
            set {
                this["Form_EquipeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Form_EquipeLocation {
            get {
                return ((global::System.Drawing.Point)(this["Form_EquipeLocation"]));
            }
            set {
                this["Form_EquipeLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("479, 400")]
        public global::System.Drawing.Size Form_JoueursSize {
            get {
                return ((global::System.Drawing.Size)(this["Form_JoueursSize"]));
            }
            set {
                this["Form_JoueursSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Form_JoueursLocation {
            get {
                return ((global::System.Drawing.Point)(this["Form_JoueursLocation"]));
            }
            set {
                this["Form_JoueursLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1190, 788")]
        public global::System.Drawing.Size Form_MatchsSize {
            get {
                return ((global::System.Drawing.Size)(this["Form_MatchsSize"]));
            }
            set {
                this["Form_MatchsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Form_MatchsLocation {
            get {
                return ((global::System.Drawing.Point)(this["Form_MatchsLocation"]));
            }
            set {
                this["Form_MatchsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("351, 201")]
        public global::System.Drawing.Size Form_DivisionsSize {
            get {
                return ((global::System.Drawing.Size)(this["Form_DivisionsSize"]));
            }
            set {
                this["Form_DivisionsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Form_DivisionsLocation {
            get {
                return ((global::System.Drawing.Point)(this["Form_DivisionsLocation"]));
            }
            set {
                this["Form_DivisionsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("399, 421")]
        public global::System.Drawing.Size Form_StatsSize {
            get {
                return ((global::System.Drawing.Size)(this["Form_StatsSize"]));
            }
            set {
                this["Form_StatsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Form_StatsLocation {
            get {
                return ((global::System.Drawing.Point)(this["Form_StatsLocation"]));
            }
            set {
                this["Form_StatsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("442, 353")]
        public global::System.Drawing.Size Form_Top3Size {
            get {
                return ((global::System.Drawing.Size)(this["Form_Top3Size"]));
            }
            set {
                this["Form_Top3Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Form_Top3Location {
            get {
                return ((global::System.Drawing.Point)(this["Form_Top3Location"]));
            }
            set {
                this["Form_Top3Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("435, 350")]
        public global::System.Drawing.Size Form_ClassementSize {
            get {
                return ((global::System.Drawing.Size)(this["Form_ClassementSize"]));
            }
            set {
                this["Form_ClassementSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Form_ClassementLocation {
            get {
                return ((global::System.Drawing.Point)(this["Form_ClassementLocation"]));
            }
            set {
                this["Form_ClassementLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("699, 416")]
        public global::System.Drawing.Size Form_CalendrierSize {
            get {
                return ((global::System.Drawing.Size)(this["Form_CalendrierSize"]));
            }
            set {
                this["Form_CalendrierSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Form_CalendrierLocation {
            get {
                return ((global::System.Drawing.Point)(this["Form_CalendrierLocation"]));
            }
            set {
                this["Form_CalendrierLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")]
        public global::System.Drawing.Font Form_Equipe_Police {
            get {
                return ((global::System.Drawing.Font)(this["Form_Equipe_Police"]));
            }
            set {
                this["Form_Equipe_Police"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Form_Equipe_CouleurPolice {
            get {
                return ((global::System.Drawing.Color)(this["Form_Equipe_CouleurPolice"]));
            }
            set {
                this["Form_Equipe_CouleurPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color Form_Equipe_CouleurForm {
            get {
                return ((global::System.Drawing.Color)(this["Form_Equipe_CouleurForm"]));
            }
            set {
                this["Form_Equipe_CouleurForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")]
        public global::System.Drawing.Font Form_Equipe_DGVPolice {
            get {
                return ((global::System.Drawing.Font)(this["Form_Equipe_DGVPolice"]));
            }
            set {
                this["Form_Equipe_DGVPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Form_Equipe_DGVCouleurPolice {
            get {
                return ((global::System.Drawing.Color)(this["Form_Equipe_DGVCouleurPolice"]));
            }
            set {
                this["Form_Equipe_DGVCouleurPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")]
        public global::System.Drawing.Font Preferences_Police {
            get {
                return ((global::System.Drawing.Font)(this["Preferences_Police"]));
            }
            set {
                this["Preferences_Police"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Preferences_CouleurPolice {
            get {
                return ((global::System.Drawing.Color)(this["Preferences_CouleurPolice"]));
            }
            set {
                this["Preferences_CouleurPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color Preferences_CouleurForm {
            get {
                return ((global::System.Drawing.Color)(this["Preferences_CouleurForm"]));
            }
            set {
                this["Preferences_CouleurForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")]
        public global::System.Drawing.Font Preferences_DGVPolice {
            get {
                return ((global::System.Drawing.Font)(this["Preferences_DGVPolice"]));
            }
            set {
                this["Preferences_DGVPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Preferences_DGVCouleurPolice {
            get {
                return ((global::System.Drawing.Color)(this["Preferences_DGVCouleurPolice"]));
            }
            set {
                this["Preferences_DGVCouleurPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font Form_Matchs_Police {
            get {
                return ((global::System.Drawing.Font)(this["Form_Matchs_Police"]));
            }
            set {
                this["Form_Matchs_Police"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Form_Matchs_CouleurPolice {
            get {
                return ((global::System.Drawing.Color)(this["Form_Matchs_CouleurPolice"]));
            }
            set {
                this["Form_Matchs_CouleurPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Form_Matchs_CouleurForm {
            get {
                return ((global::System.Drawing.Color)(this["Form_Matchs_CouleurForm"]));
            }
            set {
                this["Form_Matchs_CouleurForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font Form_Matchs_DGVPolice {
            get {
                return ((global::System.Drawing.Font)(this["Form_Matchs_DGVPolice"]));
            }
            set {
                this["Form_Matchs_DGVPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Form_Matchs_DGVCouleurPolice {
            get {
                return ((global::System.Drawing.Color)(this["Form_Matchs_DGVCouleurPolice"]));
            }
            set {
                this["Form_Matchs_DGVCouleurPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font Form_Divisions_Police {
            get {
                return ((global::System.Drawing.Font)(this["Form_Divisions_Police"]));
            }
            set {
                this["Form_Divisions_Police"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Form_Divisions_CouleurPolice {
            get {
                return ((global::System.Drawing.Color)(this["Form_Divisions_CouleurPolice"]));
            }
            set {
                this["Form_Divisions_CouleurPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Form_Divisions_CouleurForm {
            get {
                return ((global::System.Drawing.Color)(this["Form_Divisions_CouleurForm"]));
            }
            set {
                this["Form_Divisions_CouleurForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font Form_Divisions_DGVPolice {
            get {
                return ((global::System.Drawing.Font)(this["Form_Divisions_DGVPolice"]));
            }
            set {
                this["Form_Divisions_DGVPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Form_Divisions_DGVCouleurPolice {
            get {
                return ((global::System.Drawing.Color)(this["Form_Divisions_DGVCouleurPolice"]));
            }
            set {
                this["Form_Divisions_DGVCouleurPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font Form_Classement_Police {
            get {
                return ((global::System.Drawing.Font)(this["Form_Classement_Police"]));
            }
            set {
                this["Form_Classement_Police"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Form_Classement_CouleurPolice {
            get {
                return ((global::System.Drawing.Color)(this["Form_Classement_CouleurPolice"]));
            }
            set {
                this["Form_Classement_CouleurPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Form_Classement_CouleurForm {
            get {
                return ((global::System.Drawing.Color)(this["Form_Classement_CouleurForm"]));
            }
            set {
                this["Form_Classement_CouleurForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font Form_Classement_DGVPolice {
            get {
                return ((global::System.Drawing.Font)(this["Form_Classement_DGVPolice"]));
            }
            set {
                this["Form_Classement_DGVPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Form_Classement_DGVCouleurPolice {
            get {
                return ((global::System.Drawing.Color)(this["Form_Classement_DGVCouleurPolice"]));
            }
            set {
                this["Form_Classement_DGVCouleurPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font Form_Calendrier_Police {
            get {
                return ((global::System.Drawing.Font)(this["Form_Calendrier_Police"]));
            }
            set {
                this["Form_Calendrier_Police"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Form_Calendrier_CouleurPolice {
            get {
                return ((global::System.Drawing.Color)(this["Form_Calendrier_CouleurPolice"]));
            }
            set {
                this["Form_Calendrier_CouleurPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Form_Calendrier_CouleurForm {
            get {
                return ((global::System.Drawing.Color)(this["Form_Calendrier_CouleurForm"]));
            }
            set {
                this["Form_Calendrier_CouleurForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font Form_Calendrier_DGVPolice {
            get {
                return ((global::System.Drawing.Font)(this["Form_Calendrier_DGVPolice"]));
            }
            set {
                this["Form_Calendrier_DGVPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Form_Calendrier_DGVCouleurPolice {
            get {
                return ((global::System.Drawing.Color)(this["Form_Calendrier_DGVCouleurPolice"]));
            }
            set {
                this["Form_Calendrier_DGVCouleurPolice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string PositionJoueur {
            get {
                return ((string)(this["PositionJoueur"]));
            }
            set {
                this["PositionJoueur"] = value;
            }
        }
    }
}
